add endpoint that creates error for testing
i-dot-ai/ellandi pull request #382
Opened 2022-08-25 11:52 UTC by nmenezes0

2022-08-25 12:28 UTC, Singletoned requested changes

2022-08-25 12:28 UTC, Singletoned commented on api/ellandi/registration/views.py
> +@decorators.permission_classes((permissions.IsAuthenticated,))
I would consider making this admin only. Giving any logged in user the ability to throw an error might be foolhardy

2022-08-25 12:55 UTC, nmenezes0 commented on api/ellandi/registration/views.py
> +@decorators.permission_classes((permissions.IsAuthenticated,))
Have updated

2022-08-26 08:31 UTC, Singletoned approved these changes

2022-08-26 08:58 UTC, merged