Feature/email domains
i-dot-ai/ellandi pull request #433
Opened 2022-09-06 13:13 UTC by nmenezes0

2022-09-07 12:50 UTC, Singletoned requested changes

2022-09-07 12:50 UTC, Singletoned commented on api/ellandi/registration/serializers.py
> +ALLOWED_DOMAINS = [
Put this in settings

2022-09-07 12:50 UTC, Singletoned commented on api/ellandi/registration/serializers.py
> +ALLOWED_DOMAINS = [
And it should probably be a `frozenset` not a `list`

2022-09-07 15:46 UTC, nmenezes0 commented on api/ellandi/registration/serializers.py
> +ALLOWED_DOMAINS = [
Have changed.

2022-09-08 10:08 UTC, Singletoned approved these changes

2022-09-08 10:08 UTC, merged