Feature/job titles
i-dot-ai/ellandi pull request #453
Opened 2022-09-12 17:15 UTC by nmenezes0

2022-09-12 17:16 UTC, nmenezes0 commented
Fixes #442

2022-09-13 07:33 UTC, nmenezes0 commented
@rottitime - for info - this is the PR adding job titles endpoint

2022-09-14 09:22 UTC, Singletoned requested changes

2022-09-14 09:32 UTC, nmenezes0 commented on api/ellandi/registration/migrations/0009_loaddata_fixtures_jobtitles.py
> +    fixture_file = f"dropdown/jobtitles.json"
Now changed

2022-09-14 11:54 UTC, Singletoned approved these changes

2022-09-14 11:54 UTC, merged