Feature/533 lm email validation
i-dot-ai/ellandi pull request #548
Opened 2022-09-29 16:30 UTC by nmenezes0

Fixes #533

2022-09-30 09:22 UTC, Singletoned requested changes

2022-09-30 09:22 UTC, Singletoned commented on api/ellandi/registration/views.py
> +                detail = error.args[0]["detail"]
What if there is multiple errors?

2022-09-30 10:00 UTC, nmenezes0 commented on api/ellandi/registration/views.py
> +                detail = error.args[0]["detail"]
I guess we never find out what they are.... (I'll change it)

2022-10-03 08:46 UTC, nmenezes0 commented on api/ellandi/registration/views.py
> +                detail = error.args[0]["detail"]
Actually, I think if there are multiple errors then they are in that first argument as a dictionary/list (but what I've done wouldn't get them all). Have changed it slightly.

2022-10-03 10:50 UTC, Singletoned approved these changes

2022-10-03 10:50 UTC, merged