Add mentor to onboarding & profile
i-dot-ai/ellandi pull request #682
Opened 2022-10-25 08:23 UTC by aialopes

Closes:
https://trello.com/c/tzsJRsBm/167-add-mentor-question-to-sign-up-and-profile
https://trello.com/c/pRFInnDw/139-edit-profile

2022-10-25 08:42 UTC, rottitime approved these changes

2022-10-25 08:45 UTC, rottitime requested changes
seem to be errors on `npm run test:all`

2022-10-25 08:50 UTC, aialopes commented
@rottitime - Strangely enough, Jest seems happy with it 🫢
```
 /web   feature/al/167-mentor-form  npm test                                                            ✔

> test
> jest

 PASS  __tests__/account/team-id.test.tsx (5.263 s)
 PASS  components/Form/ForgottenPasswordForm/ForgottenPasswordForm.test.tsx (5.619 s)
 PASS  __tests__/account/profile.test.tsx (5.713 s)
 PASS  components/Form/ResetPasswordForm/ResetPasswordForm.test.tsx (5.767 s)
 PASS  components/Form/SignInForm/SignInForm.test.tsx (5.917 s)
 PASS  components/Account/LanguageList/LanguageList.test.tsx (6.266 s)
 PASS  components/Form/CreatableAutocomplete/CreatableAutocomplete.test.tsx (7.729 s)
 PASS  components/UI/DataGrid/DataGrid.test.tsx (7.764 s)
 PASS  components/Form/Register/CreateAccountForm/CreateAccountForm.test.tsx (8.173 s)
 PASS  components/Form/Account/SkillsAddForm/SkillsAddForm.test.tsx (8.288 s)
 PASS  __tests__/register.test.tsx
 PASS  components/Account/SkillsList/SkillsList.test.tsx (8.962 s)
 PASS  components/Form/UpdateAccountPasswordForm/UpdateAccountPasswordForm.test.tsx
 PASS  components/Form/Register/GradeForm/GradeForm.test.tsx
 PASS  components/Layout/AccountLayout/AccountLayout.test.tsx
 PASS  components/Form/FeedbackForm/FeedbackForm.test.tsx
 PASS  components/Account/LearningRecordList/LearningRecordList.test.tsx
 PASS  components/Account/SkillsDevelop/SkillsDevelop.test.tsx (9.58 s)
 PASS  components/Form/LearningAddForm/LearningAddForm.test.tsx (9.79 s)
 PASS  components/UI/SkillsSuggest/SkillsSuggest.test.tsx
 PASS  components/UI/Dialogs/WarningDialog/WarningDialog.test.tsx
 PASS  components/UI/Tabs/Tabs.test.tsx
 PASS  components/Form/Duration/Duration.test.tsx
 PASS  __tests__/forgotten-password.test.tsx
 PASS  components/UI/TextFieldControlled/TextFieldControlled.test.tsx
 PASS  __tests__/feedback.test.tsx
 PASS  __tests__/register-step.test.tsx
 PASS  __tests__/signin.test.tsx
 PASS  __tests__/email-verify.test.tsx
 PASS  __tests__/reset-password.test.tsx
 PASS  hooks/useTranslation.test.ts
 PASS  service/auth.test.ts
 PASS  components/Account/LearningGoalBar/LearningGoalBar.test.tsx
 PASS  lib/date-utils.test.ts
 PASS  lib/data-utils.test.ts
 PASS  hooks/useAuth.test.ts
 PASS  lib/url-utils.test.ts
 PASS  service/api.test.ts
 PASS  components/ConditionalWrapper/ConditionalWrapper.test.tsx
 PASS  components/UI/Button/Button.test.tsx
 PASS  service/me.test.ts
 PASS  components/Form/Register/LanguageForm/LanguageForm.test.tsx (13.631 s)
 PASS  components/Form/Register/RegisterDetailsForm/RegisterDetailsForm.test.tsx (13.696 s)

Test Suites: 43 passed, 43 total
Tests:       3 skipped, 142 passed, 145 total
Snapshots:   0 total
Time:        15.359 s
Ran all test suites.
 /web   feature/al/167-mentor-form  npm run test:all                                                    ✔

> test:all
> next lint && tsc --noemit && jest

info  - Loaded env from /Users/alopes/Projects/iai/ellandi/web/.env.local
✔ No ESLint warnings or errors
lib/test-utils.tsx:83:14 - error TS2322: Type '{ id: string; email: string; privacy_policy_agreement: true; first_name: string; last_name: string; job_title: string; is_line_manager: string; business_unit: string; department: null; location: string; ... 17 more ...; modified_at: string; }' is not assignable to type 'RegisterUserResponse'.
  Property 'is_mentor' is missing in type '{ id: string; email: string; privacy_policy_agreement: true; first_name: string; last_name: string; job_title: string; is_line_manager: string; business_unit: string; department: null; location: string; ... 17 more ...; modified_at: string; }' but required in type '{ id: string; email: string; has_direct_reports: boolean; verified: boolean; department: string; created_at: string; modified_at: string; is_line_manager: string; is_mentor: string; }'.

83 export const mockMe: RegisterUserResponse = {
                ~~~~~~

  service/types.ts:130:3
    130   is_mentor: string
          ~~~~~~~~~
    'is_mentor' is declared here.


Found 1 error in lib/test-utils.tsx:83
```

2022-10-25 09:32 UTC, rottitime commented
> @rottitime - Strangely enough, Jest seems happy with it 🫢 Should we make `test:all` the default `test` behaviour?
> 

I think this is a error with ts lint instead of jest

2022-10-26 08:28 UTC, rottitime approved these changes

2022-10-26 08:29 UTC, merged