Draft: Feature/reporting
i-dot-ai/ellandi pull request #705
Opened 2022-11-01 18:01 UTC by nmenezes0

2022-11-07 11:34 UTC, rottitime commented
@nmenezes0 I seem to get the below errors:

```
docker-compose down --volumes
docker compose up api
```

```
ellandi-api-1  | Traceback (most recent call last):
ellandi-api-1  |   File "manage.py", line 22, in <module>
ellandi-api-1  |     main()
ellandi-api-1  |   File "manage.py", line 18, in main
ellandi-api-1  |     execute_from_command_line(sys.argv)
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
ellandi-api-1  |     utility.execute()
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
ellandi-api-1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
ellandi-api-1  |     self.execute(*args, **cmd_options)
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
ellandi-api-1  |     output = self.handle(*args, **options)
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
ellandi-api-1  |     res = handle_func(*args, **kwargs)
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 75, in handle
ellandi-api-1  |     self.check(databases=[database])
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
ellandi-api-1  |     all_issues = checks.run_checks(
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
ellandi-api-1  |     new_errors = check(app_configs=app_configs, databases=databases)
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
ellandi-api-1  |     all_namespaces = _load_all_namespaces(resolver)
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
ellandi-api-1  |     url_patterns = getattr(resolver, 'url_patterns', [])
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
ellandi-api-1  |     res = instance.__dict__[self.name] = self.func(instance)
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 602, in url_patterns
ellandi-api-1  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
ellandi-api-1  |     res = instance.__dict__[self.name] = self.func(instance)
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
ellandi-api-1  |     return import_module(self.urlconf_name)
ellandi-api-1  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
ellandi-api-1  |     return _bootstrap._gcd_import(name[level:], package, level)
ellandi-api-1  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
ellandi-api-1  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
ellandi-api-1  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
ellandi-api-1  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
ellandi-api-1  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
ellandi-api-1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ellandi-api-1  |   File "/app/api/ellandi/urls.py", line 10, in <module>
ellandi-api-1  |     from ellandi import auth, reporting, verification
ellandi-api-1  |   File "/app/api/ellandi/reporting.py", line 5, in <module>
ellandi-api-1  |     from rest_framework_csv.renderers import CSVRenderer
ellandi-api-1  | ModuleNotFoundError: No module named 'rest_framework_csv'
ellandi-api-1 exited with code 1

2022-11-07 11:38 UTC, nmenezes0 commented
> 

@rottitime - I think that you have to rebuild as a I added a new package: `docker-compose up --build` (or just run `make docker`)

2022-11-07 11:59 UTC, rottitime commented
> > 
> 
> @rottitime - I think that you have to rebuild as a I added a new package: `docker-compose up --build` (or just run `make docker`)

Already discussed on slack. but for our record error on docker build

```
=> ERROR [ellandi_api  7/14] RUN python3 -m pip install -r /app/api/requirements.lock --no-cache-  4.9s
------
 > [ellandi_api  7/14] RUN python3 -m pip install -r /app/api/requirements.lock --no-cache-dir:
#0 0.746 Collecting asgiref==3.5.2
#0 0.837   Downloading asgiref-3.5.2-py3-none-any.whl (22 kB)
#0 0.870 Collecting attrs==22.1.0
#0 0.884   Downloading attrs-22.1.0-py2.py3-none-any.whl (58 kB)
#0 0.904      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 2.9 MB/s eta 0:00:00
#0 0.937 Collecting certifi==2022.9.24
#0 0.951   Downloading certifi-2022.9.24-py3-none-any.whl (161 kB)
#0 0.970      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.1/161.1 kB 9.0 MB/s eta 0:00:00
#0 1.098 Collecting cffi==1.15.1
#0 1.115   Downloading cffi-1.15.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (449 kB)
#0 1.132      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 449.9/449.9 kB 27.6 MB/s eta 0:00:00
#0 1.181 Collecting charset-normalizer==2.1.1
#0 1.197   Downloading charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
#0 1.226 Collecting click==8.1.3
#0 1.246   Downloading click-8.1.3-py3-none-any.whl (96 kB)
#0 1.251      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 26.1 MB/s eta 0:00:00
#0 1.397 Collecting cryptography==38.0.1
#0 1.430   Downloading cryptography-38.0.1-cp36-abi3-manylinux_2_28_aarch64.whl (4.0 MB)
#0 1.546      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 35.1 MB/s eta 0:00:00
#0 1.614 Collecting Django==3.2.16
#0 1.633   Downloading Django-3.2.16-py3-none-any.whl (7.9 MB)
#0 1.864      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 35.0 MB/s eta 0:00:00
#0 1.919 Collecting django-cors-headers==3.13.0
#0 1.936   Downloading django_cors_headers-3.13.0-py3-none-any.whl (13 kB)
#0 1.960 Collecting django-environ==0.9.0
#0 1.977   Downloading django_environ-0.9.0-py2.py3-none-any.whl (17 kB)
#0 1.999 Collecting django-gov-notify==0.3.0
#0 2.016   Downloading django_gov_notify-0.3.0-py3-none-any.whl (5.9 kB)
#0 2.039 Collecting django-rest-knox==4.2.0
#0 2.055   Downloading django_rest_knox-4.2.0-py3-none-any.whl (13 kB)
#0 2.100 Collecting djangorestframework==3.14.0
#0 2.117   Downloading djangorestframework-3.14.0-py3-none-any.whl (1.1 MB)
#0 2.148      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 37.5 MB/s eta 0:00:00
#0 2.169 Collecting djangorestframework-csv==2.1.1
#0 2.195   Downloading djangorestframework-csv-2.1.1.tar.gz (9.4 kB)
#0 2.199   Preparing metadata (setup.py): started
#0 2.573   Preparing metadata (setup.py): finished with status 'done'
#0 2.595 Collecting docopt==0.6.2
#0 2.613   Downloading docopt-0.6.2.tar.gz (25 kB)
#0 2.618   Preparing metadata (setup.py): started
#0 2.962   Preparing metadata (setup.py): finished with status 'done'
#0 2.994 Collecting drf-spectacular==0.24.2
#0 3.013   Downloading drf_spectacular-0.24.2-py3-none-any.whl (88 kB)
#0 3.016      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.9/88.9 kB 80.2 MB/s eta 0:00:00
#0 3.092 Collecting Faker==15.1.2
#0 3.119   Downloading Faker-15.1.2-py3-none-any.whl (1.6 MB)
#0 3.166      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 36.3 MB/s eta 0:00:00
#0 3.198 Collecting filelock==3.8.0
#0 3.214   Downloading filelock-3.8.0-py3-none-any.whl (10 kB)
#0 3.237 Collecting furl==2.1.3
#0 3.254   Downloading furl-2.1.3-py2.py3-none-any.whl (20 kB)
#0 3.285 Collecting huggingface-hub==0.10.1
#0 3.306   Downloading huggingface_hub-0.10.1-py3-none-any.whl (163 kB)
#0 3.310      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.5/163.5 kB 178.6 MB/s eta 0:00:00
#0 3.333 Collecting idna==3.4
#0 3.356   Downloading idna-3.4-py3-none-any.whl (61 kB)
#0 3.359      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 150.6 MB/s eta 0:00:00
#0 3.402 Collecting importlib-resources==5.10.0
#0 3.419   Downloading importlib_resources-5.10.0-py3-none-any.whl (34 kB)
#0 3.444 Collecting inflection==0.5.1
#0 3.460   Downloading inflection-0.5.1-py2.py3-none-any.whl (9.5 kB)
#0 3.485 Collecting Jinja2==3.1.2
#0 3.509   Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
#0 3.513      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 57.2 MB/s eta 0:00:00
#0 3.544 Collecting joblib==1.2.0
#0 3.559   Downloading joblib-1.2.0-py3-none-any.whl (297 kB)
#0 3.567      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB 46.3 MB/s eta 0:00:00
#0 3.601 Collecting jsonschema==4.16.0
#0 3.616   Downloading jsonschema-4.16.0-py3-none-any.whl (83 kB)
#0 3.620      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.1/83.1 kB 54.7 MB/s eta 0:00:00
#0 3.666 Collecting MarkupSafe==2.1.1
#0 3.682   Downloading MarkupSafe-2.1.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (26 kB)
#0 3.728 Collecting nltk==3.7
#0 3.745   Downloading nltk-3.7-py3-none-any.whl (1.5 MB)
#0 3.788      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 36.2 MB/s eta 0:00:00
#0 3.834 Collecting notifications-python-client==6.4.1
#0 3.865   Downloading notifications_python_client-6.4.1-py2.py3-none-any.whl (18 kB)
#0 4.033 Collecting numpy==1.23.4
#0 4.049   Downloading numpy-1.23.4-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (14.0 MB)
#0 4.461      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 33.7 MB/s eta 0:00:00
#0 4.496 ERROR: Could not find a version that satisfies the requirement nvidia-cublas-cu11==11.10.3.66 (from versions: 0.0.1.dev5)
#0 4.496 ERROR: No matching distribution found for nvidia-cublas-cu11==11.10.3.66
#0 4.600
#0 4.600 [notice] A new release of pip available: 22.3 -> 22.3.1
#0 4.600 [notice] To update, run: pip install --upgrade pip
------
failed to solve: executor failed running [/bin/sh -c python3 -m pip install -r /app/api/requirements.lock --no-cache-dir]: exit code: 1
make: *** [docker] Error 17

2022-11-07 12:23 UTC, rottitime commented
@nmenezes0 I get the following errors still

```
docker-compose up --build
------
 > [ellandi_api  7/14] RUN python3 -m pip install -r /app/api/requirements.lock --no-cache-dir:
#0 0.806 Collecting asgiref==3.5.2
#0 0.931   Downloading asgiref-3.5.2-py3-none-any.whl (22 kB)
#0 0.966 Collecting attrs==22.1.0
#0 0.981   Downloading attrs-22.1.0-py2.py3-none-any.whl (58 kB)
#0 0.991      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 8.3 MB/s eta 0:00:00
#0 1.017 Collecting certifi==2022.9.24
#0 1.035   Downloading certifi-2022.9.24-py3-none-any.whl (161 kB)
#0 1.048      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.1/161.1 kB 13.1 MB/s eta 0:00:00
#0 1.174 Collecting cffi==1.15.1
#0 1.194   Downloading cffi-1.15.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (449 kB)
#0 1.221      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 449.9/449.9 kB 17.0 MB/s eta 0:00:00
#0 1.270 Collecting charset-normalizer==2.1.1
#0 1.290   Downloading charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
#0 1.320 Collecting click==8.1.3
#0 1.341   Downloading click-8.1.3-py3-none-any.whl (96 kB)
#0 1.344      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 78.3 MB/s eta 0:00:00
#0 1.485 Collecting cryptography==38.0.3
#0 1.508   Downloading cryptography-38.0.3-cp36-abi3-manylinux_2_28_aarch64.whl (4.0 MB)
#0 1.624      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 34.7 MB/s eta 0:00:00
#0 1.700 Collecting Django==3.2.16
#0 1.722   Downloading Django-3.2.16-py3-none-any.whl (7.9 MB)
#0 1.964      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 33.4 MB/s eta 0:00:00
#0 2.019 Collecting django-cors-headers==3.13.0
#0 2.043   Downloading django_cors_headers-3.13.0-py3-none-any.whl (13 kB)
#0 2.066 Collecting django-environ==0.9.0
#0 2.086   Downloading django_environ-0.9.0-py2.py3-none-any.whl (17 kB)
#0 2.107 Collecting django-gov-notify==0.3.0
#0 2.125   Downloading django_gov_notify-0.3.0-py3-none-any.whl (5.9 kB)
#0 2.229 Collecting django-rest-knox==4.2.0
#0 2.248   Downloading django_rest_knox-4.2.0-py3-none-any.whl (13 kB)
#0 2.287 Collecting djangorestframework==3.14.0
#0 2.307   Downloading djangorestframework-3.14.0-py3-none-any.whl (1.1 MB)
#0 2.341      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 37.8 MB/s eta 0:00:00
#0 2.368 Collecting djangorestframework-csv==2.1.1
#0 2.393   Downloading djangorestframework-csv-2.1.1.tar.gz (9.4 kB)
#0 2.397   Preparing metadata (setup.py): started
#0 2.743   Preparing metadata (setup.py): finished with status 'done'
#0 2.769 Collecting docopt==0.6.2
#0 2.787   Downloading docopt-0.6.2.tar.gz (25 kB)
#0 2.792   Preparing metadata (setup.py): started
#0 3.132   Preparing metadata (setup.py): finished with status 'done'
#0 3.165 Collecting drf-spectacular==0.24.2
#0 3.184   Downloading drf_spectacular-0.24.2-py3-none-any.whl (88 kB)
#0 3.188      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.9/88.9 kB 51.8 MB/s eta 0:00:00
#0 3.261 Collecting Faker==15.2.0
#0 3.277   Downloading Faker-15.2.0-py3-none-any.whl (1.6 MB)
#0 3.324      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 35.8 MB/s eta 0:00:00
#0 3.354 Collecting filelock==3.8.0
#0 3.379   Downloading filelock-3.8.0-py3-none-any.whl (10 kB)
#0 3.411 Collecting furl==2.1.3
#0 3.431   Downloading furl-2.1.3-py2.py3-none-any.whl (20 kB)
#0 3.461 Collecting huggingface-hub==0.10.1
#0 3.479   Downloading huggingface_hub-0.10.1-py3-none-any.whl (163 kB)
#0 3.485      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.5/163.5 kB 121.4 MB/s eta 0:00:00
#0 3.517 Collecting idna==3.4
#0 3.535   Downloading idna-3.4-py3-none-any.whl (61 kB)
#0 3.537      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 123.6 MB/s eta 0:00:00
#0 3.575 Collecting importlib-resources==5.10.0
#0 3.592   Downloading importlib_resources-5.10.0-py3-none-any.whl (34 kB)
#0 3.612 Collecting inflection==0.5.1
#0 3.628   Downloading inflection-0.5.1-py2.py3-none-any.whl (9.5 kB)
#0 3.655 Collecting Jinja2==3.1.2
#0 3.672   Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
#0 3.675      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 130.8 MB/s eta 0:00:00
#0 3.711 Collecting joblib==1.2.0
#0 3.728   Downloading joblib-1.2.0-py3-none-any.whl (297 kB)
#0 3.736      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB 133.7 MB/s eta 0:00:00
#0 3.771 Collecting jsonschema==4.17.0
#0 3.787   Downloading jsonschema-4.17.0-py3-none-any.whl (83 kB)
#0 3.791      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.8/83.8 kB 363.6 MB/s eta 0:00:00
#0 3.840 Collecting MarkupSafe==2.1.1
#0 3.867   Downloading MarkupSafe-2.1.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (26 kB)
#0 3.914 Collecting nltk==3.7
#0 3.934   Downloading nltk-3.7-py3-none-any.whl (1.5 MB)
#0 3.977      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 36.8 MB/s eta 0:00:00
#0 4.009 Collecting notifications-python-client==6.4.1
#0 4.035   Downloading notifications_python_client-6.4.1-py2.py3-none-any.whl (18 kB)
#0 4.203 Collecting numpy==1.23.4
#0 4.227   Downloading numpy-1.23.4-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (14.0 MB)
#0 4.636      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 34.2 MB/s eta 0:00:00
#0 4.670 ERROR: Could not find a version that satisfies the requirement nvidia-cublas-cu11==11.10.3.66 (from versions: 0.0.1.dev5)
#0 4.670 ERROR: No matching distribution found for nvidia-cublas-cu11==11.10.3.66
#0 4.761
#0 4.761 [notice] A new release of pip available: 22.3 -> 22.3.1
#0 4.761 [notice] To update, run: pip install --upgrade pip
------
failed to solve: executor failed running [/bin/sh -c python3 -m pip install -r /app/api/requirements.lock --no-cache-dir]: exit code: 1
```

```
make docker
------
 > [ellandi_api  7/14] RUN python3 -m pip install -r /app/api/requirements.lock --no-cache-dir:
#0 1.253 Collecting asgiref==3.5.2
#0 1.358   Downloading asgiref-3.5.2-py3-none-any.whl (22 kB)
#0 1.389 Collecting attrs==22.1.0
#0 1.405   Downloading attrs-22.1.0-py2.py3-none-any.whl (58 kB)
#0 1.413      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 11.0 MB/s eta 0:00:00
#0 1.441 Collecting certifi==2022.9.24
#0 1.463   Downloading certifi-2022.9.24-py3-none-any.whl (161 kB)
#0 1.477      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.1/161.1 kB 11.9 MB/s eta 0:00:00
#0 1.590 Collecting cffi==1.15.1
#0 1.607   Downloading cffi-1.15.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (449 kB)
#0 1.627      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 449.9/449.9 kB 24.9 MB/s eta 0:00:00
#0 1.670 Collecting charset-normalizer==2.1.1
#0 1.689   Downloading charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
#0 1.719 Collecting click==8.1.3
#0 1.737   Downloading click-8.1.3-py3-none-any.whl (96 kB)
#0 1.741      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 95.9 MB/s eta 0:00:00
#0 1.875 Collecting cryptography==38.0.3
#0 1.898   Downloading cryptography-38.0.3-cp36-abi3-manylinux_2_28_aarch64.whl (4.0 MB)
#0 2.012      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 35.1 MB/s eta 0:00:00
#0 2.080 Collecting Django==3.2.16
#0 2.106   Downloading Django-3.2.16-py3-none-any.whl (7.9 MB)
#0 2.335      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 34.7 MB/s eta 0:00:00
#0 2.407 Collecting django-cors-headers==3.13.0
#0 2.423   Downloading django_cors_headers-3.13.0-py3-none-any.whl (13 kB)
#0 2.445 Collecting django-environ==0.9.0
#0 2.466   Downloading django_environ-0.9.0-py2.py3-none-any.whl (17 kB)
#0 2.489 Collecting django-gov-notify==0.3.0
#0 2.508   Downloading django_gov_notify-0.3.0-py3-none-any.whl (5.9 kB)
#0 2.532 Collecting django-rest-knox==4.2.0
#0 2.551   Downloading django_rest_knox-4.2.0-py3-none-any.whl (13 kB)
#0 2.588 Collecting djangorestframework==3.14.0
#0 2.609   Downloading djangorestframework-3.14.0-py3-none-any.whl (1.1 MB)
#0 2.645      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 31.2 MB/s eta 0:00:00
#0 2.669 Collecting djangorestframework-csv==2.1.1
#0 2.694   Downloading djangorestframework-csv-2.1.1.tar.gz (9.4 [...]

2022-11-07 17:10 UTC, rottitime commented
@nmenezes0 `total_users` always seems to return `2`. Can you update this to return the total number of users that have added the particular  language or skill. I need this for the following AC

```
Default table order to be most - least added languages (based on total number of people with that language)

2022-11-07 20:57 UTC, nmenezes0 commented
> @nmenezes0 `total_users` always seems to return `2`. Can you update this to return the total number of users that have added the particular language or skill. I need this for the following AC
> 
> ```
> Default table order to be most - least added languages (based on total number of people with that language)
> ```

Which endpoint is that for? I'm getting the right amount of `total_users` (I think) 

For the languages I'm getting:
```
{
  "total": 2,
  "data": [
    {
      "name": "French",
      "type": "writing",
      "total_users": 1068,
      "language_value_total": 1,
      "language_value_percentage": 0,
      "basic_value_total": 0,
      "basic_value_percentage": 0,
      "basic_label": "0 (0%)",
      "independent_value_total": 1,
 ```
And tests appear to be running fine too.

Could it be something to do with your local data?

2022-11-07 21:09 UTC, rottitime commented
> And tests appear to be running fine too.
> 
> Could it be something to do with your local data?

You could be right in that case. I will double check tomorrow then

2022-11-08 13:45 UTC, Singletoned requested changes
Use admin permissions and remove all the comments

2022-11-08 13:45 UTC, Singletoned commented on api/ellandi/reporting.py
> +    # FIXME - doesn't work in SQLite
This doesn't need fixing anymore

2022-11-08 13:45 UTC, Singletoned commented on api/ellandi/reporting.py
> +        percentage_at_each_level = [(x / number_with_skill) * 100 for x in number_at_each_level]
You should always multiply before you divide for higher precision

2022-11-08 13:45 UTC, Singletoned commented on api/ellandi/reporting.py
> +@decorators.permission_classes((permissions.IsAuthenticated,))
Make it admin only for now

2022-11-08 13:45 UTC, Singletoned commented on api/tests/test_reporting.py
> +# FIXME - this test doesn't work is cos SQLite doesn't have `contained_by`
Is fixed

2022-11-08 13:45 UTC, Singletoned commented on api/tests/test_reporting.py
> +# TODO - need to think about permissions for reporting
Use admin permission

2022-11-08 15:25 UTC, Singletoned approved these changes

2022-11-08 15:25 UTC, merged