Find courses tab
i-dot-ai/ellandi pull request #714
Opened 2022-11-03 13:10 UTC by aialopes

Closes https://trello.com/c/kTOuwRgu/219-learning-find-courses-tab

2022-11-09 12:52 UTC, rottitime commented
@aialopes The learning 'goal' and 'distribution' are now components in:

- components/Account/LearningGoalBar/LearningGoalBar.tsx
- components/Account/LearningDistribution/LearningDistribution.tsx

2022-11-15 09:58 UTC, rottitime requested changes

2022-11-15 09:58 UTC, rottitime commented on web/pages/account/learning/courses.tsx
> +const LearningRecordRedirect = () => {
`LearningRecordRedirect ` can be deleted. Tabs already have redirect attribute in place

2022-11-15 09:58 UTC, rottitime commented on web/pages/account/learning/courses.tsx
> +            title: 'Learning record',
change to

```
            content: null,
            href: '/account/learning/'

2022-11-15 09:58 UTC, rottitime commented on web/pages/account/learning/index.tsx
> +            content: <FindCoursesRedirect />
Replace with 

```
            content: null,
            href: '/account/learning/courses'

2022-11-15 09:58 UTC, rottitime commented on web/components/Account/FindCourses.tsx
> +                style={{
Can you move background-color to `/UI/Select/Select` as this needs to sit globally.

Also we already have a attribute for fullwidth. Delete `width` and `max-width` and add `fullWidth` to `Select`

```
              <Select
                fullWidth

2022-11-15 10:14 UTC, aialopes commented on web/package.json
> +    "date-fns": "^2.29.3",
Yes. Had a check on their repo and it doesn't offer the same exact feature.

2022-11-15 10:30 UTC, rottitime approved these changes

2022-11-15 10:31 UTC, merged