Feature/learning duration
i-dot-ai/ellandi pull request #860
Opened 2022-12-02 16:01 UTC by nmenezes0

We can have really long courses and costs e.g. apprenticeship.

2022-12-09 08:55 UTC, Singletoned requested changes
Whack in another test that checks that it gracefully handles an amount thats too large

2022-12-10 13:47 UTC, Singletoned commented
I've added in a test that actually "checks that it gracefully handles an amount thats too large"

2022-12-10 13:53 UTC, Singletoned approved these changes

2022-12-10 13:53 UTC, merged

2022-12-12 12:01 UTC, nmenezes0 commented
> I've added in a test that actually "checks that it gracefully handles an amount thats too large"

I would actually have done this you know! (I was just too busy interviewing/emailing facilities about cat poo on Friday.)